<a href="https://colab.research.google.com/github/michelleaeh/CE888_Laboratory/blob/master/Laboratory1/Laboratory1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Laboratory 1
## 1-15-2020



### Questions to be done during the lab:
**1. Create a (4 x 2) integer array and print it's attributes**



In [0]:
import numpy as np
a=np.array([[0, 1],
            [2, 3], 
            [4, 5],
            [6, 7]])
print(a)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]


**2. Create an array of dimension (1,10) and sort it in ascending and descending order**



In [0]:
b=[2, 26, 98, 4, 19, 1, 6, 26, 71, 3, 14, 70, 20]

# https://www.geeksforgeeks.org/python-list-sort/
b.sort()
print("The array in ascending order is", b)

# https://www.geeksforgeeks.org/python-list-sort/
b.sort(reverse=True)
print("The array in descending order is", b)

The array in ascending order is: [1, 2, 3, 4, 6, 14, 19, 20, 26, 26, 70, 71, 98]
The array in descending order is: [98, 71, 70, 26, 26, 20, 19, 14, 6, 4, 3, 2, 1]


**3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]**

In [0]:
# https://stackoverflow.com/questions/12575421/convert-a-1d-array-to-a-2d-array-in-numpy
c=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
d=np.reshape(c,(-1,3))
print(d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


**4. Stack two arrays of any size horizontally and vertically**

In [0]:
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html
f=np.array([4, 6, 9, 3, 3])
g=np.array([7, 1, 5, 0, 1])
print("Horizontal stack:")
print(np.stack((f,g)))
print("Vertical stack:")
print(np.stack((f,g),axis=-1))

Horizontal stack:
[[4 6 9 3 3]
 [7 1 5 0 1]]
Vertical stack:
[[4 7]
 [6 1]
 [9 5]
 [3 0]
 [3 1]]


**5. Create two array of same size and find commom elements**



In [0]:
# https://www.codespeedy.com/find-the-common-elements-in-two-lists-in-python/ 
h=np.array([21, 18, 49, 48])
j=np.array([49, 24, 17, 21])
def common(h,j):
  com=[value for value in h if value in j]
  return com 
print("The common elements are", common(h,j))

The common elements are  [21, 49]


**6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column**



In [0]:
# https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html
# https://stackoverflow.com/questions/42610617/minimum-value-in-each-row-and-each-column-of-a-matrix-python
k=np.random.rand(5,5)
print("The array is")
print(k)

print("The min values of each row are", np.min(k,axis=1))
print("The min values of each column are", np.min(k,axis=0))

The array is
[[0.01550141 0.4869076  0.62844371 0.91076333 0.59366142]
 [0.32508703 0.41852288 0.95088631 0.65987616 0.05746663]
 [0.44990152 0.8591997  0.32642421 0.8694952  0.54245034]
 [0.59700356 0.78611226 0.65969689 0.55584862 0.85777495]
 [0.88327985 0.97830856 0.51730117 0.3391217  0.62439135]]
The min values of each row are  [0.01550141 0.05746663 0.32642421 0.55584862 0.3391217 ]
The min values of each column are  [0.01550141 0.41852288 0.32642421 0.3391217  0.05746663]


**7. Create an array of size 100 and compute the mean, median, standard deviation.**



In [0]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html 
m=np.random.rand(100)
print("The mean of the array is", np.mean(m))
print("The median of the array is", np.median(m))
print("The standard deviation of the array is", np.std(m))

The mean of the array is 0.48920515648887347
The median of the array is 0.4911300546165085
The standard deviation of the array is 0.29885507253891364


**8. Normalize a 5x5 random matrix**



In [0]:
# https://stackoverflow.com/questions/21030391/how-to-normalize-an-array-in-numpy
n=np.random.rand(5,5)
print("The original array is")
print(n)
print("The normalized array is")
print(normalize(n,copy=False))


The original array is
[[0.98896402 0.89259854 0.739849   0.69106374 0.68385116]
 [0.00712069 0.63228315 0.83723802 0.75466218 0.57567431]
 [0.56533413 0.3958879  0.34932043 0.20042267 0.87873611]
 [0.46401124 0.41484915 0.29772696 0.5304152  0.81638355]
 [0.17654546 0.50173775 0.02411946 0.64330417 0.3838415 ]]
The normalized array is
[[0.54711758 0.49380598 0.40930143 0.38231231 0.37832214]
 [0.00503293 0.44690002 0.59176285 0.53339795 0.40688868]
 [0.4759789  0.3333149  0.29410776 0.16874439 0.7398454 ]
 [0.38886005 0.34766025 0.24950715 0.44450924 0.68416221]
 [0.19209418 0.54592683 0.02624371 0.69996129 0.4176472 ]]


**9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?**

In [0]:
#https://stackoverflow.com/questions/46930268/numpy-multiple-3d-array-with-a-2d-array
p=np.random.rand(4,4,3)
q=np.random.rand(4,4)

q.dot(q.T)

array([[1.96946361, 2.18507508, 1.3473702 , 0.790146  ],
       [2.18507508, 2.55222413, 1.53334319, 0.91327894],
       [1.3473702 , 1.53334319, 1.20267127, 0.69110085],
       [0.790146  , 0.91327894, 0.69110085, 0.64265666]])